### ISSUE TITLE
Not compatible with macOS's bash 3.2

### ISSUE THREAD

**Issue by bra1ncramp** [cisagov/gh-skeleton#27]
# 🐛 Summary #

`gh-skeleton` is not compatible with older version of Bash. The operator, `;;&` to fork the process in the `case` statement in order to match multiple conditions, is not supported in macOS's version of bash.

## To reproduce ##

install `cisagov/gh-skeleton`
```gh extension install cisagov/gh-skeleton```
use the 'skeleton` command
```gh skeleton list```

get error:
```/Users/someusername/.local/share/gh/extensions/gh-skeleton/gh-skeleton: line 168: syntax error near unexpected token `&'```

## Expected behavior ##

```
% gh skeleton list
Available skeletons in cisagov:

skeleton-ansible-role    	A skeleton project for quickly getting a new cisagov Ansible role started.
skeleton-ansible-role-with-test-user	A skeleton project for quickly getting a new cisagov Ansible role started when that role requires an AWS test user.
skeleton-aws-lambda-python	A skeleton project for quickly getting a new Python-based AWS Lambda project started.
skeleton-docker          	A skeleton project for quickly getting a new cisagov Docker container started.
skeleton-generic         	A generic skeleton project for quickly getting a new cisagov project started.
skeleton-packer          	A skeleton project for quickly getting a new cisagov packer project started.
skeleton-python-library  	A skeleton project for quickly getting a new cisagov Python library started.
skeleton-tf-module       	A skeleton project for quickly getting a new cisagov Terraform module started.

```

## Suggested solution ##
change the following code from:
```
  case $remote_repo_status in
    created)
      log_ok "The remote repository ${dest_org}/${dest_repo} was successfully created."
      ;;&
    exists)
      log_info "The remote repository ${dest_org}/${dest_repo} already existed."
      ;;&
    created | exists)
      log_info "Pushing ${DEFAULT_BRANCH} and first-commit branches to the remote."
      git push origin "${DEFAULT_BRANCH}" first-commits --set-upstream
      log_info "Opening a new pull request for the first-commits branch."
      gh pr create --title "First commits" --assignee=@me --web
      ;;

```

to:

```
  case $remote_repo_status in
    created)
      log_ok "The remote repository ${dest_org}/${dest_repo} was successfully created."
      ;;
    exists)
      log_info "The remote repository ${dest_org}/${dest_repo} already existed."
      ;;
  esac
  case $remote_repo_status in
    created | exists)
      log_info "Pushing ${DEFAULT_BRANCH} and first-commit branches to the remote."
      git push origin "${DEFAULT_BRANCH}" first-commits --set-upstream
      log_info "Opening a new pull request for the first-commits branch."
      gh pr create --title "First commits" --assignee=@me --web
      ;;

```

**Comment by jsf9k** [comment]
@dav3r, @felddy, or @mcdonnnj - Why has this not popped up before, on your machines?

**Comment by dav3r** [comment]
Probably because none of us use the ancient version of `bash` that ships with macOS:
```
❱ /bin/bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)
Copyright (C) 2007 Free Software Foundation, Inc.
```

Not sure about @mcdonnnj, but both @felddy and I use `brew` to install a more modern version than Apple prefers.

**Comment by mcdonnnj** [comment]
I also have an updated version from `brew`. Supporting the ancient version of `bash` that ships with macOS (from 2007 I think?) is probably a non-starter.

**Comment by jsf9k** [comment]
> I also have an updated version from `brew`. Supporting the ancient version of `bash` that ships with macOS (from 2007 I think?) is probably a non-starter.

I couldn't agree more.  I'm inclined to add the `won't fix` label and close this issue.

**Comment by jsf9k** [comment]
We can't be expected to live with the c2007 version of `bash` that ships with OSX.  Folks should install an updated `bash` from Brew or similar.
