### ISSUE TITLE
Generate initial version 

### ISSUE THREAD

**Issue by jasonodoom** [cisagov/gh-skeleton#31]
# 💡 Summary #

When a new repository is being created from the skeleton, the skeleton's version number should be ignored and be replaced with a standard initial version such as `0.0.1`.

## Motivation and context ##

Each skeleton repository has its own version. If a new repository descends from a skeleton it should not inherit the skeleton's version number and should start from a new version number such as `0.0.1`.

## Implementation notes ##

The `bump_version.sh` script could possibly be used to implement this feature, if that script was modified to force the version to a specific version (in this case, it would set the new repo's version to `0.0.1`, regardless of what the skeleton's version was).

## Acceptance criteria ##

The script should be able to do what is discussed.

- [ ] When `gh-skeleton clone` is run, the newly-created repository is initialized to the standard version number (e.g. `0.0.1`) rather than inheriting the current version number of the parent skeleton.

**Comment by jsf9k** [comment]
This would be a nice improvement.

**Comment by mcdonnnj** [comment]
If a repository has a `bump-version` script you can expect to get the list of files that use the version of the project with `bump-version --list-files` once it has been implemented.
